import { useGetFeaturedSectionsQuery } from "../features/featured-sections/api"
import HomeTemplate from "../pattern-library/templates/home"
import Head from "next/head"

function Home() {
  const { isSuccess, data } = useGetFeaturedSectionsQuery()

  return (
    <div>
      <Head>
        <title>Electric Cars, Solar & Clean Energy | Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isSuccess ? (
        <div className="font-montserrat">
          <HomeTemplate sections={data} />
        </div>
      ) : undefined}
    </div>
  )
}

export default Home
