import fetchAllFeaturedSections from "../features/featured-sections/fetch-all"
import HomeTemplate from "../pattern-library/templates/home"
import { dehydrate, QueryClient, useQuery } from "@tanstack/react-query"
import Head from "next/head"

export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(
    ["featuredSections"],
    fetchAllFeaturedSections
  )

  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    }
  }
}

function Home() {
  const { data } = useQuery(["featuredSections"], fetchAllFeaturedSections)

  return (
    <div>
      <Head>
        <title>Electric Cars, Solar & Clean Energy | Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="font-montserrat">
        <HomeTemplate sections={data} />
      </div>
    </div>
  )
}

export default Home
